image: ruby:2.7

pages:
  script:
    - gem install bundler
    - bundle install
    - JEKYLL_ENV=production bundle exec jekyll build -d public/
  artifacts:
    paths:
      - public
  only:
    - main
