theme: jekyll-theme-minimal
title: Octocat's homepage
description: Bookmark this to keep an eye on my project updates!
pages:
  image: node:latest
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
    - npm ci
  artifacts:
    paths:
      - public
  only:
    - main
